SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT t.ITEM_ID
                 FROM ITEM_INFO i, ITEM_TREE t
                 WHERE i.ITEM_ID = t.PARENT_ITEM_ID
                 AND i.RARITY = 'RARE')
ORDER BY ITEM_ID DESC;