SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE AS G
JOIN HR_EMPLOYEES AS E ON E.EMP_NO = G.EMP_NO
JOIN HR_DEPARTMENT AS D ON E.DEPT_ID = D.DEPT_ID
WHERE G.YEAR = '2022'
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;